version: "3.4"
volumes:
  app-postgresql:
services:
  postgres:
    container_name: app-postgresql
    image: postgres:12.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_dev
    ports:
      - "5432:5432"
    volumes:
      - app-postgresql:/var/lib/postgresql/data
    logging:
      options:
        max-file: "5"
        max-size: "10m"
